<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="basicAnnotations" duration-ms="113" started-at="2017-10-02T04:25:38Z" finished-at="2017-10-02T04:25:38Z">
    <groups>
      <group name="regression">
        <method signature="DependsOnTest.login()[pri:0, instance:testNG.DependsOnTest@68c4039c]" name="login" class="testNG.DependsOnTest"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="DependsOnTest.login()[pri:0, instance:testNG.DependsOnTest@68c4039c]" name="login" class="testNG.DependsOnTest"/>
      </group> <!-- sanity -->
    </groups>
    <test name="basicAnnoations" duration-ms="9" started-at="2017-10-02T04:25:38Z" finished-at="2017-10-02T04:25:38Z">
    </test> <!-- basicAnnoations -->
    <test name="dependsOnTest" duration-ms="38" started-at="2017-10-02T04:25:38Z" finished-at="2017-10-02T04:25:38Z">
      <class name="testNG.DependsOnTest">
        <test-method status="FAIL" signature="login()[pri:0, instance:testNG.DependsOnTest@68c4039c]" name="login" duration-ms="16" started-at="2017-10-02T17:25:38Z" finished-at="2017-10-02T17:25:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testNG.DependsOnTest.login(DependsOnTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="SKIP" signature="logout()[pri:0, instance:testNG.DependsOnTest@68c4039c]" name="logout" duration-ms="1" started-at="2017-10-02T17:25:38Z" depends-on-methods="testNG.DependsOnTest.login" finished-at="2017-10-02T17:25:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="SKIP" signature="test2()[pri:0, instance:testNG.DependsOnTest@68c4039c]" name="test2" duration-ms="0" started-at="2017-10-02T17:25:38Z" depends-on-methods="testNG.DependsOnTest.login" finished-at="2017-10-02T17:25:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- testNG.DependsOnTest -->
    </test> <!-- dependsOnTest -->
    <test name="ParametersTest" duration-ms="24" started-at="2017-10-02T04:25:38Z" finished-at="2017-10-02T04:25:38Z">
      <class name="testNG.ParametersInTestNG">
        <test-method status="PASS" signature="testLogin(java.lang.String, java.lang.String)[pri:0, instance:testNG.ParametersInTestNG@42e26948]" name="testLogin" duration-ms="3" started-at="2017-10-02T17:25:38Z" finished-at="2017-10-02T17:25:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[amy]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
      </class> <!-- testNG.ParametersInTestNG -->
    </test> <!-- ParametersTest -->
  </suite> <!-- basicAnnotations -->
</testng-results>
