<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ammu-PC" name="TC001_loginWithInvalidData" tests="3" failures="3" timestamp="27 Sep 2017 01:51:11 GMT" time="23.708" errors="0">
  <testcase name="loginWithInvalidDataTest" time="4.926" classname="com.test.autiomation.UIAutomation1.authenticationpage.TC001_loginWithInvalidData">
    <failure type="java.lang.AssertionError" message="VerifyErrorMsg expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VerifyErrorMsg expected [true] but found [false]
	at com.test.autiomation.UIAutomation1.authenticationpage.TC001_loginWithInvalidData.loginWithInvalidDataTest(TC001_loginWithInvalidData.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidDataTest -->
  <testcase name="loginWithInvalidDataTest" time="3.639" classname="com.test.autiomation.UIAutomation1.authenticationpage.TC001_loginWithInvalidData">
    <failure type="java.lang.AssertionError" message="VerifyErrorMsg expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VerifyErrorMsg expected [true] but found [false]
	at com.test.autiomation.UIAutomation1.authenticationpage.TC001_loginWithInvalidData.loginWithInvalidDataTest(TC001_loginWithInvalidData.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidDataTest -->
  <testcase name="loginWithInvalidDataTest" time="3.752" classname="com.test.autiomation.UIAutomation1.authenticationpage.TC001_loginWithInvalidData">
    <failure type="java.lang.AssertionError" message="VerifyErrorMsg expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VerifyErrorMsg expected [true] but found [false]
	at com.test.autiomation.UIAutomation1.authenticationpage.TC001_loginWithInvalidData.loginWithInvalidDataTest(TC001_loginWithInvalidData.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidDataTest -->
</testsuite> <!-- TC001_loginWithInvalidData -->
